[features]
seeds = false
skip-lint = false
[programs.localnet]
green_dapp = "43wWGRGGehT2SuNzfC1CBwgjLEZC1uBY8fB6KXAB5HGE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/limeiro/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
